version: "3.8"
services:
#  elevators-postgres:
#    image: postgres
#    container_name: elevators-postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: zaq1@WSX
#      POSTGRES_DB: elevatorsystem
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend/.
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend/:/app
      - ./deploy/elevatorsystem-0.0.1-SNAPSHOT.jar:/app.jar
    ports:
      - "8000:8080"
    environment:
      - JAVA_OPTS=-Xmx512m


  frontend:
    container_name: frontend
    build:
      context: ./frontend/elevatorsystem
      dockerfile: ../../docker/frontend/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:4200"

  nginx:
    container_name: http
    restart: always
    build:
        context: ./nginx
        dockerfile: ../docker/nginx/Dockerfile
    ports:
        - "8080:8080"
    depends_on:
        -   "backend"
        -   "frontend"

#volumes:
#    postgres: