### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/elevator-system/start

###
POST http://localhost:8080/elevator-system/pickup HTTP/1.1
Content-Type: application/json

{
    "floor": 3,
    "direction": 1
}

###
POST http://localhost:8080/elevator-system/step

###
GET http://localhost:8080/elevator-system/status

###
POST http://localhost:8080/elevator-system/update
Content-Type: application/json
